### ISSUE TITLE
Trained Model Weights for Transfer Learning

### ISSUE THREAD

**Issue by dlphil** [pedropro/TACO#10]
Greatly appreciate this project and the amount of work that has gone into it from the developers and the community! My university team and I are undertaking a project to research automated waste detection mechanisms, and this project is perfectly aligned with the objectives of our investigation. 
Would it be possible to also share the trained weights for the MASK R-CNN model, such that these can be used as part of a transfer learning strategy? Thanks!

**Comment by pedropro** [comment]
Done. https://github.com/pedropro/TACO/releases/tag/1.0
