### ISSUE TITLE
annotions - bbox coordinate order

### ISSUE THREAD

**Issue by mtourne** [pedropro/TACO#2]
from the code I think bbox list is ordered as (ymin, xmin, ymax, xmax)
Is this correct?

it would be nicer to have that explicitly spelled out in the annotations.json

**Comment by pedropro** [comment]
Hi Matthieu ,
We are using the COCO format: http://cocodataset.org/#format-data
So it is: `{x_min, y_min, width, height}` relative to the image top-left corner.

Sorry, I am adding this info to the README.
The `demo.pynb` has a section that shows how to visualize the bboxes.

**Comment by pedropro** [comment]
Apologies, the `y_min` is, as it stands, the distance from the bottom of the object to the image bottom. You have probably realized this by now. This will change to the above.
https://github.com/pedropro/TACO/issues/8#issuecomment-564605885
