### ISSUE TITLE
Working configuration

### ISSUE THREAD

**Issue by LorenzoMonti** [pedropro/TACO#31]
Hi, 

first of all thank you for the project. I tried to launch the script detector.py. After all the dependency was installed, I launched the script that return me the error: AttributeError: module 'tensorflow' has no attribute 'log'. The error is certainly due to the tensorflow version installed in my laptop.  Referring to issue #17, Python 3.5, Keras 2.0.8, and Tensorflow 1.3.0 seems to work. But the question is: is there a newer working configuration? 

Thank you in advance,
Lorenzo

**Comment by SolidOrange** [comment]
I'm getting a similar issue when trying to run the imports in detector.ipynb. Getting `AttributeError: module 'keras.engine' has no attribute 'Layer'`. I'm sure this also has to do with the wrong versions of tensorflow and keras. 

A solution to prevent this from happening would most likely to be to add version numbers to the requirements.txt file.

**Comment by LorenzoMonti** [comment]
Right, thanks.
