### ISSUE TITLE
Annotations seem wrong

### ISSUE THREAD

**Issue by BouweCeunen** [pedropro/TACO#8]
If you look at this image
 `{"id": 561, "width": 2448, "height": 3264, "file_name": "batch_6/000031.JPG", "license": null, "flickr_url": "https://farm66.staticflickr.com/65535/47066796004_01600acd87_o.png", "coco_url": null, "date_captured": null, "flickr_640_url": "https://farm66.staticflickr.com/65535/47066796004_8f22c4f60c_z.jpg"}` 
which has an annotation
 `{"id": 1625, "image_id": 561, "category_id": 29, "segmentation": [[1258.0, 1598.0, 1266.0, 1599.0, 1278.0, 1607.0, 1284.0, 1623.0, 1285.0, 1638.0, 1313.0, 1641.0, 1322.0, 1624.0, 1330.0, 1587.0, 1341.0, 1571.0, 1354.0, 1551.0, 1335.0, 1537.0, 1315.0, 1531.0, 1289.0, 1529.0, 1269.0, 1536.0, 1274.0, 1555.0, 1271.0, 1570.0, 1262.0, 1590.0, 1258.0, 1598.0]], "area": 6447.0, "bbox": [1258.0, 1623.0, 96.0, 112.0], "iscrowd": 0}`

If I draw this on the image with left top corner (0,0), I get the following image. 
<img width="613" alt="Screenshot 2019-12-11 at 15 15 46" src="https://user-images.githubusercontent.com/5576686/70629044-9824b200-1c29-11ea-9902-158935e5dcfe.png">

I see this across all images. It seems to be mirrored across the middle. If I do `y=image_height - object_y - object-height`, I get the correct y coordinate.

**Comment by pedropro** [comment]
Yes, as it stands, the bbox `y` coordinate is the distance from the bottom of the object to the bottom of the image (inherited from labelbox). The demo notebook takes this into account.
I will upload a corrected version of annotations soon to maintain consistency with COCO format. Thanks.

**Comment by BouweCeunen** [comment]
Hi @pedropro , thanks!
